#!/bin/bash

set -x -e

PYTHON_VERSION="2.7.12"

PYDEBUG="--with-pydebug"
PYDEBUG=""

BASEDIR=`pwd`
output_dir=$BASEDIR/iosbuild
rm -rf $output_dir/arm

if [ ! -f $output_dir/host/bin/python ]; then
    make clean || true

    mkdir -p $output_dir/host
    # create Python Host version
    export CC=
    export CXX=

    cd $BASEDIR/Modules/gevent110ext/c-ares
    rm -f ares_build.h ares_config.h
    CONFIG_COMMANDS= CONFIG_FILES= ./configure

    cd $BASEDIR/Modules/gevent110ext/libev
    rm -f config.h
    ./configure

    cd $BASEDIR
    ./configure --prefix=$output_dir/host
    nice make -j4
    nice make -j4 Parser/pgen
    mv Parser/pgen $output_dir/host
    make install
fi

MY_HOSTPYTHON=$output_dir/host/bin/python
MY_HOSTPGEN=$output_dir/host/pgen

function build
{
    make clean || true

    local HOST=$1; local ARCH=$2; local SDK=$3; local OUTPUT=$4
    shift 4


    mkdir -p /tmp/pyios/$OUTPUT

    SDK_PATH=$(xcrun -sdk $SDK --show-sdk-path)
    GCC=$(xcrun -sdk $SDK -find gcc)
    FLAGS=$@
    export CC="${GCC} -arch ${ARCH} -isysroot ${SDK_PATH} $FLAGS"
    export CXX=$CC

    cd $BASEDIR/Modules/gevent110ext/c-ares
    rm -f ares_build.h ares_config.h Makefile
    CONFIG_COMMANDS= CONFIG_FILES= ./configure --host=$HOST --build=x86_64-apple-darwin14.3.0

    cd $BASEDIR/Modules/gevent110ext/libev

    rm -f config.h Makefile
    ./configure --host=$HOST --build=x86_64-apple-darwin14.3.0

    cd $BASEDIR

    rm -f Makefile
    ./configure CONFIG_SITE=config.site.ndk HOSTPYTHON=$MY_HOSTPYTHON HOSTPGEN=$MY_HOSTPGEN --prefix="/tmp/pyios/$OUTPUT" --host=$HOST --build=x86_64-apple-darwin14.3.0 --disable-toolbox-glue --disable-ipv6 $PYDEBUG

    gsed -i "s|^INSTSONAME=\(.*.so\).*|INSTSONAME=\\1|g" Makefile
    nice make -j4 HOSTPYTHON=$MY_HOSTPYTHON HOSTPGEN=$MY_HOSTPGEN CROSS_COMPILE=$HOST- CROSS_COMPILE_TARGET=yes libpython2.7.a
    mv libpython2.7.a /tmp/pyios/$OUTPUT
}

function build-fat
{
    DIR=$1; OUTPUT=$2;
    lipo $DIR/*/libpython2.7.a -create -output $OUTPUT
}

build aarch64-apple-darwin arm64 iphoneos arm64 -fembed-bitcode -miphoneos-version-min=9.1 -fno-omit-frame-pointer # -DPY_FORMAT_LONG_LONG=ll
build armv7-apple-darwin armv7 iphoneos armv7 -fembed-bitcode -miphoneos-version-min=9.1 -fno-omit-frame-pointer -mno-thumb
# build i386-apple-darwin i386 iphonesimulator i386 -fembed-bitcode -miphoneos-version-min=9.1 -fno-omit-frame-pointer

build-fat /tmp/pyios libpython2.7.a
