#!/bin/bash

set -x

PYTHON_VERSION="2.7.9"

PYDEBUG="--with-pydebug"
PYDEBUG=""

BASEDIR=`pwd`
output_dir=$BASEDIR/iosbuild
rm -rf $output_dir/arm

if [ ! -f $output_dir/host/bin/python ]; then
    mkdir -p $output_dir/host
    # create Python Host version
    ./configure --prefix=$output_dir/host
    nice make -j4
    nice make -j4 Parser/pgen
    mv Parser/pgen $output_dir/host
    make install
    make clean
fi

MY_HOSTPYTHON=$output_dir/host/bin/python
MY_HOSTPGEN=$output_dir/host/pgen

function build
{
    local HOST=$1; local ARCH=$2; local SDK=$3; local OUTPUT=$4

    mkdir -p /tmp/pyios/$OUTPUT

    make clean

    SDK_PATH=$(xcrun -sdk $SDK --show-sdk-path)
    GCC=$(xcrun -sdk $SDK -find gcc)
    export CC="${GCC} -arch ${ARCH} -isysroot ${SDK_PATH} -fno-omit-frame-pointer"
    export CXX=$CC

    if ! ./configure CONFIG_SITE=config.site.ndk HOSTPYTHON=$MY_HOSTPYTHON HOSTPGEN=$MY_HOSTPGEN --prefix="/tmp/pyios/$OUTPUT" --host=$HOST --build=x86_64-apple-darwin --disable-toolbox-glue --disable-ipv6 $PYDEBUG; then
        exit 1;
    fi

    cd $BASEDIR/Modules/gevent110ext/c-ares
    rm -f ares_build.h ares_config.h
    CONFIG_COMMANDS= CONFIG_FILES= ./configure --host=$HOST --build=x86_64-apple-darwin14.3.0

    cd $BASEDIR/Modules/gevent110ext/libev
    rm -f config.h
    ./configure --host=$HOST --build=x86_64-apple-darwin14.3.0

    cd $BASEDIR

    sed -i "s|^INSTSONAME=\(.*.so\).*|INSTSONAME=\\1|g" Makefile
    nice make -j4 HOSTPYTHON=$MY_HOSTPYTHON HOSTPGEN=$MY_HOSTPGEN CROSS_COMPILE=$HOST- CROSS_COMPILE_TARGET=yes
    mv libpython2.7.a /tmp/pyios/$OUTPUT
}

function build-fat
{
    DIR=$1; OUTPUT=$2;
    lipo $DIR/*/libpython2.7.a -create -output $OUTPUT
}

build aarch64-apple-darwin arm64 iphoneos arm64
build armv7-apple-darwin armv7 iphoneos armv7
build armv7s-apple-darwin armv7s iphoneos armv7s
build i386-apple-darwin i386 macosx i386

build-fat /tmp/pyios libpython2.7.a
