#!/bin/sh

echo "Begins at android 5.0, not usable now"
exit 1

export ANDROID_NDK=~/android-ndk-r12b
export ANDROID_ABI="arm64-v8a"
export ANDROID_NATIVE_API_LEVEL="android-15"
export PATH="$ANDROID_NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/:$ANDROID_NDK:$ANDROID_NDK/tools:/usr/local/bin:/usr/bin:/bin"
export ARCH=$ANDROID_ABI
# export CFLAGS="-DANDROID -mandroid -fomit-frame-pointer --sysroot $ANDROID_NDK/platforms/$ANDROID_NATIVE_API_LEVEL/arch-arm"
export CFLAGS="-mandroid -g -fno-omit-frame-pointer --sysroot $ANDROID_NDK/platforms/$ANDROID_NATIVE_API_LEVEL/arch-arm"
export CPPFLAGS="-DANDROID"

# export CFLAGS="-DANDROID -mandroid -g -O0 --sysroot $ANDROID_NDK/platforms/$ANDROID_NATIVE_API_LEVEL/arch-arm"

export CXXFLAGS="$CFLAGS"
export CC="aarch64-linux-android-gcc $CFLAGS"
export CXX="aarch64-linux-android-g++ $CXXFLAGS"
export AR="aarch64-linux-android-ar"
export RANLIB="aarch64-linux-android-ranlib"
export STRIP="aarch64-linux-android-strip --strip-unneeded"
